version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mydb
      PMA_PORT: 3306
    networks:
      - dockercompose-frontend
    depends_on:
      - mydb

  mydb:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dockercompose-frontend
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pexample || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

networks:
  dockercompose-frontend:
    driver: bridge

volumes:
  mysql-data:
