version: '3.8'

services:
  mydb:
    image: mariadb:latest
    build:
      context: ./mydb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - dockercompose-frontend
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mydb
      PMA_PORT: 3306
    depends_on:
      mydb:
        condition: service_healthy
    networks:
      - dockercompose-frontend

networks:
  dockercompose-frontend:

volumes:
  mysql-data: