version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mydb
      PMA_PORT: 3306
    networks:
      - dockercompose-frontend
    depends_on:
      mydb:
        condition: service_healthy

  mydb:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dockercompose-frontend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 5

networks:
  dockercompose-frontend:
    driver: bridge

volumes:
  mysql-data: