version: "3.3"

services:
  mydb:
    build:
      context: ./mydb
    image: mydb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - frontend
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 5

  phpmyadmin:
    build:
      context: ./phpmyadmin
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=mydb
      - PMA_PORT=3306
    ports:
      - "8080:80"
    depends_on:
      - mydb
    networks:
      - frontend

networks:
  frontend:
    name: dockercompose-frontend

volumes:
  mysql_data:
