version: "3.3"

services:
  mydb:
    image: mysql:5.7
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 15s
      retries: 5
    volumes:
      - mydb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      mydb:
        condition: service_healthy
    environment:
      PMA_HOST: mydb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    command: >
      sh -c "while ! mysqladmin ping -h mydb --silent; do sleep 1; done &&
      phpmyadmin-entrypoint"

  mysql-dump:
    image: mysql:5.7
    container_name: mysql-dump
    command: >
      bash -c "
      while ! mysqladmin ping -h mydb --silent; do sleep 1; done &&
      while true; do
        mysqldump -h mydb -u root -prootpassword mydb > /backup/mydb.sql;
        sleep 60;
      done"
    depends_on:
      mydb:
        condition: service_healthy
    volumes:
      - ./task-13:/backup

volumes:
  mydb-data:
