version: '3.9'

services:
  mydb:
    build:
      context: ./mydb
      dockerfile: Dockerfile
    image: custom-mariadb
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 15s
      retries: 5
    networks:
      - frontend

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    image: custom-phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mydb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      mydb:
        condition: service_healthy
    networks:
      - frontend

volumes:
  mysql-data:

networks:
  frontend:
    name: dockercompose-frontend
